### ISSUE TITLE
mHuBERT model for it/de/nl

### ISSUE THREAD

**Issue by zhouyan19** [choijeongsoo/utut#1]
Your document mentions that the mHuBERT for extracting units comes from the repo of textless_s2st_real_data, however, the repo does not provide models for it/de/nl languages. May I ask how this was resolved in your paper?

**Comment by choijeongsoo** [comment]
In our paper, we utilized the mHuBERT of textless_s2st_real_data repository for quantizing speech in it/de/nl languages. Although the mHuBERT model was trained on en/es/fr languages, we found that it can be used for unseen languages.

**Comment by zhouyan19** [comment]
> In our paper, we utilized the mHuBERT of textless_s2st_real_data repository for quantizing speech in it/de/nl languages. Although the mHuBERT model was trained on en/es/fr languages, we found that it can be used for unseen languages.

Thank you! I will try doing this.
